# Generated by Django 4.1.7 on 2023-07-02 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payApi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='donatemodel',
            name='paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='donatemodel',
            name='pay_no',
            field=models.CharField(default=1, max_length=100, unique=True),
        ),
    ]
