# Generated by Django 4.1.7 on 2023-07-02 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payApi', '0002_donatemodel_paid_donatemodel_pay_no'),
    ]

    operations = [
        migrations.RenameField(
            model_name='donatemodel',
            old_name='pay_no',
            new_name='payment_id',
        ),
    ]
